name: Automatic Latest Version Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
     
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Restore NuGet Packages
      run: nuget restore AutoResequencer.sln
 
    - name: Build
      run: msbuild AutoResequencer.sln /p:Configuration=Debug
 
    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: AutoResequencer_bleeding_edge
        path: AutoResequencer\obj\x86\Debug\AutoResequencer.exe
